version: '3.8'
services:
  db:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-otus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_USER: ${POSTGRES_USER:-otus}
    volumes:
      - otus:/var/lib/postgresql/data:rw
    ports:
      - "5435:5432"
volumes:
  otus: